defaultEntryPoints = ["http", "https"]

[entryPoints]

# http should be redirected to https
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"

[entryPoints.https]
address = ":443"

# Enable ACME (Let's Encrypt): automatic SSL
[entryPoints.https.tls]
[acme]
email = "madan_limbu@hotmail.co.uk"
storage = "acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "madanlimbu.com"
watch = true
exposedbydefault = false
