version: '3'

services:
  wordpress:
    image: wordpress
    container_name: wordpress_container
    restart: always
    volumes: # Mount docker server to www directory
      - ./www:/var/www/html
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traffic"
      - "traefik.frontend.rule=Host:${WORDPRESS_DOMAIN}.${BASE_URL}"
      - "traefik.port=80"
    networks:
      - traffic
networks:
  traffic:
    external: true
